### ISSUE TITLE
Built-in Seashell functions!

### ISSUE THREAD

**Issue by x-daniel-17** [SeasideDevs/Seashell#41]
This issue will track the progress of Seashell’s built-in functions to help developers make bots faster and easier :D

Features to be made
- Moderation functions
Options: log (sends to log channel(s)), dm (sends a dm to the user)
- Log functions [Send logs to certain channels in a server]
Functions: 
- logs.send (sends a log)
Options: channels (channels to send to), logContent (what to put in the log, can be an embed or just text).

More things will be added with time.

**Comment by TheLimifiedLime** [comment]
Was reopened in the rewrite repo
